sonar.projectKey=SyntaxDevopsSquad-SDS_devops-syntaxsquad
sonar.organization=syntaxdevopssquad-sds
sonar.cpd.go.minimumTokens=150
sonar.cpd.exclusions=/*.go
sonar.cpd.exclusions=/routes.go,**/handlers.go